name: Check & Cachix
description: "build the NixOS Moudle and push to cachix"
inputs:
  cachix_auth_token:
    description: "cachix auth token"
    required: true
runs:
  using: composite
  steps:
    - uses: cachix/cachix-action@v10
      with:
        name: slaier
        authToken: "${{ inputs.cachix_auth_token }}"
    - run: nix -Lv flake check --show-trace
      shell: bash
    - run: nix -Lv build ".#nixosConfigurations.pc.config.system.build.toplevel"
      shell: bash
