# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  material-fox = {
    pname = "material-fox";
    version = "8b1a7b10da0751a1f63e51eac428ba1eb1094b5f";
    src = fetchFromGitHub ({
      owner = "muckSponge";
      repo = "MaterialFox";
      rev = "8b1a7b10da0751a1f63e51eac428ba1eb1094b5f";
      fetchSubmodules = false;
      sha256 = "sha256-une3WS6mprqga8FuNRlZV0a3Vmq7UhL1Gzy4JvdRov4=";
    });
  };
}
