name: Update inputs
on:
  schedule:
    # rebuild at 8:11 on Friday
    - cron: "11 8 * * 5"
  workflow_dispatch:
jobs:
  update_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Install nix
        uses: cachix/install-nix-action@v19
        with:
          install_url: https://releases.nixos.org/nix/nix-2.13.3/install
      - name: Update flake lock
        run: |
          git checkout -B wip-update-inputs
          git config user.name "dependabot[bot]"
          git config user.email "<49699333+dependabot[bot]@users.noreply.github.com>"
          nix flake update --commit-lock-file --commit-lockfile-summary "nix(deps): update inputs"
          git push origin wip-update-inputs --force-with-lease
      - name: Trigger Workflow
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'test.yml',
              ref: 'wip-update-inputs',
            })
