name: Update inputs
on:
  schedule:
    # rebuild at 8:11 on Friday
    - cron: "11 8 * * 5"
  workflow_dispatch:
jobs:
  update_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-22.11
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Update inputs
        run: |
          git config user.name "dependabot[bot]"
          git config user.email "<49699333+dependabot[bot]@users.noreply.github.com>"
          nix flake update --commit-lock-file --commit-lockfile-summary "nix(deps): update inputs"
          nix develop --command just update
          git add .
          git commit --amend --no-edit
          git push origin HEAD:wip-update-inputs --force-with-lease
      - name: Trigger Workflow
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'test.yml',
              ref: 'wip-update-inputs',
            })
